name: ci

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal
      - name: Pack
        run: dotnet pack src/WalnutDb/WalnutDb.csproj -c Release -o ./artifacts
      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: nupkg
          path: artifacts/*.nupkg
